
// This file has been generated by the GUI designer. Do not modify.
namespace JuegoDeCartasGTK
{
	public partial class Prueba
	{
		private global::Gtk.Fixed fixed1;

		private global::Gtk.Button button1;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget JuegoDeCartasGTK.Prueba
			this.Name = "JuegoDeCartasGTK.Prueba";
			this.Title = global::Mono.Unix.Catalog.GetString("Prueba");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child JuegoDeCartasGTK.Prueba.Gtk.Container+ContainerChild
			this.fixed1 = new global::Gtk.Fixed();
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.button1 = new global::Gtk.Button();
			this.button1.CanFocus = true;
			this.button1.Name = "button1";
			this.button1.UseUnderline = true;
			this.button1.Label = global::Mono.Unix.Catalog.GetString("GtkButton");
			this.fixed1.Add(this.button1);
			global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button1]));
			w1.X = 264;
			w1.Y = 96;
			this.Add(this.fixed1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show();
		}
	}
}
